name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build + test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev] pytest build twine

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 trustpy --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 trustpy --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Run unit tests
        run: |
          PYTHONPATH=. pytest tests/

      - name: Build package
        run: |
          python -m build

      - name: Check package metadata
        run: |
          twine check dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
