name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build + test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev] pytest build twine

      - name: Run unit tests
        run: |
          PYTHONPATH=. pytest tests/
